In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\bsrik\OneDrive\Desktop\Global_Superstore2.csv", encoding="latin1")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [4]:
df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [5]:
df.shape

(51290, 24)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

In [7]:
df = df.drop_duplicates()

In [8]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

C:\Users\bsrik\AppData\Local\Temp\ipykernel_29080\2772104420.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Order Date"] = pd.to_datetime(df["Order Date"])
C:\Users\bsrik\AppData\Local\Temp\ipykernel_29080\2772104420.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  datetime64[ns]
 3   Ship Date       51290 non-null  datetime64[ns]
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: datetime64[ns](2), float64(5), int64(2), object(15)
memory usage: 9.4+ MB

In [10]:
df["Order Year"] = df["Order Date"].dt.year

In [11]:
df["Order Month"] = df["Order Date"].dt.month

In [12]:
df["Month Name"] = df["Order Date"].dt.month_name()

In [13]:
df["Quarter"] = df["Order Date"].dt.quarter

In [14]:
df["Shipping Days"] = (
    df["Ship Date"] - df["Order Date"]
).dt.days

In [15]:
df["Profit Margin %"] = (
    df["Profit"] / df["Sales"]
) * 100

In [16]:
df[df["Sales"] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority, Order Year, Order Month, Month Name, Quarter, Shipping Days, Profit Margin %]
Index: []

[0 rows x 30 columns]

In [17]:
df[df["Quantity"] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, City, State, Country, Postal Code, Market, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Shipping Cost, Order Priority, Order Year, Order Month, Month Name, Quarter, Shipping Days, Profit Margin %]
Index: []

[0 rows x 30 columns]

In [18]:
df["Discount"].describe()

count    51290.000000
mean         0.142908
std          0.212280
min          0.000000
25%          0.000000
50%          0.000000
75%          0.200000
max          0.850000
Name: Discount, dtype: float64

In [19]:
df[df["Profit"] < 0]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Discount,Profit,Shipping Cost,Order Priority,Order Year,Order Month,Month Name,Quarter,Shipping Days,Profit Margin %
1,26341,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,0.1,-288.7650,923.63,Critical,2013,2,February,1,2,-7.784693
3,13524,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,0.1,-96.5400,910.16,Medium,2013,1,January,1,2,-3.337586
9,40936,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,0.4,-1862.3124,865.74,Critical,2012,1,January,1,3,-43.333333
30,220,US-2011-128776,2011-12-28,2011-12-30,Second Class,RR-19525,Rick Reed,Corporate,Santo Domingo,Santo Domingo,...,0.2,-148.4600,704.06,Critical,2011,12,December,4,2,-8.750236
32,32735,CA-2012-139731,2012-10-15,2012-10-15,Same Day,JE-15745,Joel Eaton,Consumer,Amarillo,Texas,...,0.3,-350.4900,690.42,High,2012,10,October,4,0,-14.285714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51276,31558,US-2014-155299,2014-06-09,2014-06-13,Standard Class,Dl-13600,Dorris liebe,Corporate,Pasadena,Texas,...,0.8,-4.4660,0.02,Medium,2014,6,June,2,4,-275.000000
51278,43818,NI-2011-4700,2011-09-08,2011-09-10,Second Class,PO-8865,Patrick O'Donnell,Consumer,Lagos,Lagos,...,0.7,-6.4560,0.02,High,2011,9,September,3,2,-120.357942
51279,46231,ZI-2011-4350,2011-03-21,2011-03-26,Standard Class,AS-285,Alejandro Savely,Corporate,Harare,Harare,...,0.7,-21.1680,0.02,Medium,2011,3,March,1,5,-220.224719
51280,46582,TU-2014-6730,2014-11-29,2014-11-30,First Class,KF-6285,Karen Ferguson,Home Office,Midyat,Mardin,...,0.6,-49.5720,0.02,Medium,2014,11,November,4,1,-145.253165
51286,35398,US-2014-102288,2014-06-20,2014-06-24,Standard Class,ZC-21910,Zuschuss Carroll,Consumer,Houston,Texas,...,0.8,-1.1100,0.01,Medium,2014,6,June,2,4,-250.000000

In [20]:
df.to_csv(
    "Global_Superstore_Cleaned.csv",
    index=False
)

In [21]:
df.shape

(51290, 30)

In [22]:
df.duplicated().sum()

0

In [23]:
df.isnull().sum()

Row ID                 0
Order ID               0
Order Date             0
Ship Date              0
Ship Mode              0
Customer ID            0
Customer Name          0
Segment                0
City                   0
State                  0
Country                0
Postal Code        41296
Market                 0
Region                 0
Product ID             0
Category               0
Sub-Category           0
Product Name           0
Sales                  0
Quantity               0
Discount               0
Profit                 0
Shipping Cost          0
Order Priority         0
Order Year             0
Order Month            0
Month Name             0
Quarter                0
Shipping Days          0
Profit Margin %        0
dtype: int64

In [24]:
df.drop(columns=["Postal Code"], inplace=True)

In [25]:
print("Total Sales:", df["Sales"].sum())

print("Total Profit:", df["Profit"].sum())

print("Total Orders:", df["Order ID"].nunique())

print("Total Customers:", df["Customer ID"].nunique())

Total Sales: 12642501.909880001
Total Profit: 1467457.29128
Total Orders: 25035
Total Customers: 1590

In [26]:
profit_margin = (
    df["Profit"].sum()
    /
    df["Sales"].sum()
) * 100

print(profit_margin)

11.607332960995603

In [27]:
country_sales = (
    df.groupby("Country")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

country_sales

Country
United States     2.297201e+06
Australia         9.252359e+05
France            8.589311e+05
China             7.005620e+05
Germany           6.288400e+05
Mexico            6.225906e+05
India             5.896501e+05
United Kingdom    5.285763e+05
Indonesia         4.048875e+05
Brazil            3.611064e+05
Name: Sales, dtype: float64

In [28]:
product_sales=df.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).head(10)
product_sales

Product Name
Apple Smart Phone, Full Size                                86935.7786
Cisco Smart Phone, Full Size                                76441.5306
Motorola Smart Phone, Full Size                             73156.3030
Nokia Smart Phone, Full Size                                71904.5555
Canon imageCLASS 2200 Advanced Copier                       61599.8240
Hon Executive Leather Armchair, Adjustable                  58193.4841
Office Star Executive Leather Armchair, Adjustable          50661.6840
Harbour Creations Executive Leather Armchair, Adjustable    50121.5160
Samsung Smart Phone, Cordless                               48653.4600
Nokia Smart Phone, with Caller ID                           47877.7857
Name: Sales, dtype: float64

In [29]:
df.groupby("Category").agg({
    "Sales":sum,
    "Profit":"sum"
}).sort_values(
    by="Sales",ascending=False
)

                        Sales        Profit
Category
Technology       4.744557e+06  663778.73318
Furniture        4.110874e+06  285204.72380
Office Supplies  3.787070e+06  518473.83430

In [30]:
df.groupby("Segment").agg({
    "Sales":"sum",
    "Profit":"sum"
})

                    Sales        Profit
Segment
Consumer     6.507949e+06  749239.78206
Corporate    3.824698e+06  441208.32866
Home Office  2.309855e+06  277009.18056

In [31]:
df.groupby("Region").agg({
    "Sales":"sum",
    "Profit":"sum"
}).sort_values(
    by="Sales",
    ascending=False
)

                       Sales        Profit
Region
Central         2.822303e+06  311403.98164
South           1.600907e+06  140355.76618
North           1.248166e+06  194597.95252
Oceania         1.100185e+06  120089.11200
Southeast Asia  8.844232e+05   17852.32900
North Asia      8.483098e+05  165578.42100
EMEA            8.061613e+05   43897.97100
Africa          7.837732e+05   88871.63100
Central Asia    7.528266e+05  132480.18700
West            7.254578e+05  108418.44890
East            6.787812e+05   91522.78000
Caribbean       3.242809e+05   34571.32104
Canada          6.692817e+04   17817.39000

In [32]:
df.groupby("Discount").agg({
    "Sales":"sum",
    "Profit":"sum"
})

                 Sales        Profit
Discount
0.000     6.992411e+06  1.770695e+06
0.002     2.613956e+05  5.797658e+04
0.070     1.216169e+05  2.114850e+04
0.100     1.579606e+06  2.590642e+05
0.150     3.060298e+05  2.737590e+04
0.170     2.473992e+05  2.816307e+04
0.200     1.203832e+06  1.177159e+05
0.202     1.621565e+04 -5.952727e+02
0.250     8.805535e+04  8.005875e+02
0.270     8.935167e+04 -1.675079e+03
0.300     1.889320e+05 -1.968585e+04
0.320     1.449346e+04 -2.391138e+03
0.350     9.570649e+04 -1.416965e+04
0.370     3.161802e+04 -5.806202e+03
0.400     5.595252e+05 -1.437485e+05
0.402     3.373387e+04 -1.143045e+04
0.450     3.339113e+04 -1.360679e+04
0.470     8.343217e+04 -3.116225e+04
0.500     3.241311e+05 -1.586299e+05
0.550     6.308658e+03 -3.150672e+03
0.570     8.144802e+03 -6.313548e+03
0.600     1.845819e+05 -1.639547e+05
0.602     4.977181e+03 -4.905419e+03
0.650     6.579815e+03 -6.221966e+03
0.700     1.397722e+05 -1.863505e+05
0.800     2.046333e+04 -3.861623e+04
0.850     7.968420e+02 -3.068658e+03

In [33]:
top_customers=(
    df.groupby("Customer Name").agg({
        "Sales":"sum",
        "Profit":"sum"
    }
    ).sort_values(
        by="Sales",
        ascending=False
    ).head(10)
)
top_customers

                          Sales      Profit
Customer Name
Tom Ashbrook        40488.07080  6311.97910
Tamara Chand        37457.33300  8672.89890
Greg Tran           35550.95428  5214.13118
Christopher Conant  35187.07640  5603.33370
Sean Miller         35170.93296  -409.70634
Bart Watters        32310.44650  3595.88590
Natalie Fritzler    31781.25850  1542.82110
Fred Hopkins        30400.67452  4609.29112
Jane Waco           30288.45030  6265.84570
Hunter Lopez        30243.56658  7816.56778

In [34]:
top_products = (
    df.groupby("Product Name")
      .agg({
          "Sales":"sum",
          "Profit":"sum"
      })
      .sort_values(
          by="Sales",
          ascending=False
      )
      .head(10)
)

top_products

                                                         Sales      Profit
Product Name
Apple Smart Phone, Full Size                        86935.7786   5921.5786
Cisco Smart Phone, Full Size                        76441.5306  17238.5206
Motorola Smart Phone, Full Size                     73156.3030  17027.1130
Nokia Smart Phone, Full Size                        71904.5555   9938.1955
Canon imageCLASS 2200 Advanced Copier               61599.8240  25199.9280
Hon Executive Leather Armchair, Adjustable          58193.4841   5997.2541
Office Star Executive Leather Armchair, Adjustable  50661.6840   4710.9840
Harbour Creations Executive Leather Armchair, A...  50121.5160  10427.3260
Samsung Smart Phone, Cordless                       48653.4600   -198.0900
Nokia Smart Phone, with Caller ID                   47877.7857   9465.3257

In [35]:
df["Discount Band"] = pd.cut(
    df["Discount"],
    bins=[-1,0,0.1,0.2,0.3,1],
    labels=[
        "No Discount",
        "0-10%",
        "10-20%",
        "20-30%",
        "30%+"
    ]
)

In [36]:
discount_analysis = (
    df.groupby("Discount Band")
      .agg({
          "Sales":"sum",
          "Profit":"sum"
      })
)

discount_analysis

                      Sales        Profit
Discount Band
No Discount    6.992411e+06  1.770695e+06
0-10%          1.962619e+06  3.381893e+05
10-20%         1.757261e+06  1.732548e+05
20-30%         3.825547e+05 -2.115561e+04
30%+           1.547656e+06 -7.935265e+05

In [37]:
aov = (
    df["Sales"].sum()
    /
    df["Order ID"].nunique()
)

print(aov)

504.9930860746955

In [38]:
df.to_csv(
    "Global_Superstore_Cleaned.csv",
    index=False
)

In [39]:
print(df.columns.tolist())

['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country', 'Market', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Shipping Cost', 'Order Priority', 'Order Year', 'Order Month', 'Month Name', 'Quarter', 'Shipping Days', 'Profit Margin %', 'Discount Band']